### ISSUE TITLE
Flakey billable occurrences spec

### ISSUE THREAD

**Issue by katelovescode** [pieforproviders/pieforproviders#624]
## 📋 Summary
```
Randomized with seed 63151

Failures:

  1) billable occurrences API behaves like admins and resource owners can retrieve a record /api/v1/billable_occurrences/{id} get on the right api version when authenticated resource owner billable_occurrence found returns a 200 response
     Failure/Error: @child.current_child_approval.update!(subsidy_rule: subsidy_rule)
     
     NoMethodError:
       undefined method `update!' for nil:NilClass
     Shared Example Group: "admins and resource owners can retrieve a record" called from ./spec/requests/api/v1/billable_occurrences_spec.rb:27
     # ./app/services/subsidy_rule_associator.rb:31:in `illinois_subsidy_rule_associator'
     # ./app/services/subsidy_rule_associator.rb:19:in `associate_subsidy_rule'
     # ./app/services/subsidy_rule_associator.rb:13:in `call'
     # ./app/models/child.rb:65:in `associate_subsidy_rule'
```

Had an intermittent failure with this test

## 💻 Implementation Details

> **NOTE TO ENGINEERS**
> 
> Please ensure that you are running Google Lighthouse and/or WebAIM (Wave) on any UI elements in your pull request to check for accessibility issues.
> 
> If it is out of scope to address those accessibility issues in your pull request (because the issue is in a parent component and needs refactoring to work, for example), **you are responsible for noting those issues in your pull request and writing bug tickets to address the issues - make sure you link the new tickets in your pull request**
